# Generated by Django 4.0 on 2021-12-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('service_type', models.CharField(max_length=255)),
                ('service_description', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('barcode', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
