# Generated by Django 4.0 on 2021-12-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash')], default='pending', max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='servicebill',
            options={'ordering': ['barcode']},
        ),
    ]
